### ISSUE TITLE
Could you please share which paper this code corresponds to

### ISSUE THREAD

**Issue by fzallen** [kailugaji/Fuzzy_Clustering_Algorithms#1]
Could you please share which paper this code corresponds to

**Comment by fzallen** [comment]
And why do you use the munkres algorithm in label_map to get new_label?

**Comment by kailugaji** [comment]
These three algorithms are classic fuzzy clustering algorithms, which you can refer to:
FCM: D. Tran and M. Wagner, "Fuzzy entropy clustering," Ninth IEEE International Conference on Fuzzy Systems. FUZZ- IEEE 2000 (Cat. No.00CH37063), San Antonio, TX, USA, 2000, pp. 152-157 vol.1, doi: 10.1109/FUZZY.2000.838650.
FSC: G. Gan and J. Wu. 2008. A convergence theorem for the fuzzy subspace clustering (FSC) algorithm. Pattern Recogn. 41, 6 (June, 2008), 1939–1947. https://doi.org/10.1016/j.patcog.2007.11.011.
MEC: N. B. Karayiannis, "MECA: maximum entropy clustering algorithm," Proceedings of 1994 IEEE 3rd International Fuzzy Systems Conference, Orlando, FL, USA, 1994, pp. 630-635 vol.1, doi: 10.1109/FUZZY.1994.343658.
         or D. Tran and M. Wagner, "Fuzzy entropy clustering," Ninth IEEE International Conference on Fuzzy Systems. FUZZ- IEEE 2000 (Cat. No.00CH37063), San Antonio, TX, USA, 2000, pp. 152-157 vol.1, doi: 10.1109/FUZZY.2000.838650.

The reference for label_map comes from https://github.com/huajh/dVB

**Comment by fzallen** [comment]
Thank you very much!
